/**
 * Generated by the evidence media script (python3 + PIL + ffmpeg); do not edit by hand.
 * Real sizes of the placeholder files served from public/mock/evidence.
 */
export interface EvidenceMedia {
  url: string;
  sizeBytes: number;
  mediaType: string;
  durationSec?: number;
}

export const EVIDENCE_MEDIA = {
  "CP-52202-01-button.png": {
    "url": "/mock/evidence/CP-52202-01-button.png",
    "sizeBytes": 69140,
    "mediaType": "image/png"
  },
  "CP-52202-02-download.png": {
    "url": "/mock/evidence/CP-52202-02-download.png",
    "sizeBytes": 75316,
    "mediaType": "image/png"
  },
  "CP-52202-03-nonlegal-hidden.png": {
    "url": "/mock/evidence/CP-52202-03-nonlegal-hidden.png",
    "sizeBytes": 68453,
    "mediaType": "image/png"
  },
  "CP-52202-before-after.mp4": {
    "url": "/mock/evidence/CP-52202-before-after.mp4",
    "sizeBytes": 290613,
    "durationSec": 102,
    "mediaType": "video/mp4"
  },
  "CP-52202-contact-sheet.png": {
    "url": "/mock/evidence/CP-52202-contact-sheet.png",
    "sizeBytes": 102368,
    "mediaType": "image/png"
  },
  "agreement-progress-filters.png": {
    "url": "/mock/evidence/agreement-progress-filters.png",
    "sizeBytes": 67036,
    "mediaType": "image/png"
  },
  "agreement-progress-flag-off.png": {
    "url": "/mock/evidence/agreement-progress-flag-off.png",
    "sizeBytes": 34157,
    "mediaType": "image/png"
  },
  "agreement-progress-page.png": {
    "url": "/mock/evidence/agreement-progress-page.png",
    "sizeBytes": 64337,
    "mediaType": "image/png"
  },
  "api-post-login-context.png": {
    "url": "/mock/evidence/api-post-login-context.png",
    "sizeBytes": 40255,
    "mediaType": "image/png"
  },
  "api-response.png": {
    "url": "/mock/evidence/api-response.png",
    "sizeBytes": 46191,
    "mediaType": "image/png"
  },
  "audit-log-entry.png": {
    "url": "/mock/evidence/audit-log-entry.png",
    "sizeBytes": 45216,
    "mediaType": "image/png"
  },
  "e2e-report-failed.png": {
    "url": "/mock/evidence/e2e-report-failed.png",
    "sizeBytes": 39785,
    "mediaType": "image/png"
  },
  "e2e-report.png": {
    "url": "/mock/evidence/e2e-report.png",
    "sizeBytes": 35868,
    "mediaType": "image/png"
  },
  "export-streaming.png": {
    "url": "/mock/evidence/export-streaming.png",
    "sizeBytes": 71949,
    "mediaType": "image/png"
  },
  "export-timeout.png": {
    "url": "/mock/evidence/export-timeout.png",
    "sizeBytes": 73569,
    "mediaType": "image/png"
  },
  "generic-contact-sheet.png": {
    "url": "/mock/evidence/generic-contact-sheet.png",
    "sizeBytes": 132080,
    "mediaType": "image/png"
  },
  "generic-session.mp4": {
    "url": "/mock/evidence/generic-session.mp4",
    "sizeBytes": 118291,
    "durationSec": 16,
    "mediaType": "video/mp4"
  },
  "privacy-reacceptance-prompt-es.png": {
    "url": "/mock/evidence/privacy-reacceptance-prompt-es.png",
    "sizeBytes": 33778,
    "mediaType": "image/png"
  },
  "privacy-reacceptance-prompt.png": {
    "url": "/mock/evidence/privacy-reacceptance-prompt.png",
    "sizeBytes": 32401,
    "mediaType": "image/png"
  },
  "terms-gate-modal-es.png": {
    "url": "/mock/evidence/terms-gate-modal-es.png",
    "sizeBytes": 35734,
    "mediaType": "image/png"
  },
  "terms-gate-modal.png": {
    "url": "/mock/evidence/terms-gate-modal.png",
    "sizeBytes": 36020,
    "mediaType": "image/png"
  }
} as const satisfies Record<string, EvidenceMedia>;

export type EvidenceMediaName = keyof typeof EVIDENCE_MEDIA;
